using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using System.ComponentModel.DataAnnotations;
using Erep.ViewModels.ViewModels;
namespace Erep.DomainClasses.Entities
{
    //
    public class CountryEntity
    {
        public List<CountryViewModel> Countries = new List<CountryViewModel>() {
            new CountryViewModel{Id= 1,Name= "Romania",NamePersian="رومانی"},
            new CountryViewModel{Id= 2,Name= "",NamePersian=""},
            new CountryViewModel{Id= 3,Name= "",NamePersian=""},
            new CountryViewModel{Id= 4,Name= "",NamePersian=""},
            new CountryViewModel{Id= 5,Name= "",NamePersian=""},
            new CountryViewModel{Id= 6,Name= "",NamePersian=""},
            new CountryViewModel{Id= 7,Name= "",NamePersian=""},
            new CountryViewModel{Id= 8,Name= "",NamePersian=""},
            new CountryViewModel{Id= 9,Name= "Brazil",NamePersian="برزیل"},
            new CountryViewModel{Id= 10,Name= "Italy",NamePersian="ایتالیا"},
            new CountryViewModel{Id= 11,Name= "France",NamePersian="فرانسه"},
            new CountryViewModel{Id= 12,Name= "Germany",NamePersian="آلمان"},
            new CountryViewModel{Id= 13,Name= "Hungary",NamePersian="مجارستان"},
            new CountryViewModel{Id= 14,Name= "China",NamePersian="چین"},
            new CountryViewModel{Id= 15,Name= "Spain",NamePersian="اسپانیا"},
            new CountryViewModel{Id= 16,Name= "",NamePersian=""},
            new CountryViewModel{Id= 17,Name= "",NamePersian=""},
            new CountryViewModel{Id= 18,Name= "",NamePersian=""},
            new CountryViewModel{Id= 19,Name= "",NamePersian=""},
            new CountryViewModel{Id= 20,Name= "",NamePersian=""},
            new CountryViewModel{Id= 21,Name= "",NamePersian=""},
            new CountryViewModel{Id= 22,Name= "",NamePersian=""},
            new CountryViewModel{Id= 23,Name= "Canada",NamePersian="کانادا"},
            new CountryViewModel{Id= 24,Name= "USA",NamePersian="آمریکا"},
            new CountryViewModel{Id= 25,Name= "",NamePersian=""},
            new CountryViewModel{Id= 26,Name= "Mexico",NamePersian="مکزیک"},
            new CountryViewModel{Id= 27,Name= "Argentina",NamePersian="آرژانتین"},
            new CountryViewModel{Id= 28,Name= "Venezuela",NamePersian="ونزوئلا"},
            new CountryViewModel{Id= 29,Name= "United Kingdom",NamePersian="انگلیس"},
            new CountryViewModel{Id= 30,Name= "Switzerland",NamePersian="سوئیس"},
            new CountryViewModel{Id= 31,Name= "Netherlands",NamePersian="هلند"},
            new CountryViewModel{Id= 32,Name= "Belgium",NamePersian="بلژیک"},
            new CountryViewModel{Id= 33,Name= "Austria",NamePersian="اتریش"},
            new CountryViewModel{Id= 34,Name= "Czech Republic",NamePersian="چک"},
            new CountryViewModel{Id= 35,Name= "Poland",NamePersian="لهستان"},
            new CountryViewModel{Id= 36,Name= "Slovakia",NamePersian="سلواکی"},
            new CountryViewModel{Id= 37,Name= "Norway",NamePersian="نروژ"},
            new CountryViewModel{Id= 38,Name= "Sweden",NamePersian="سوئد"},
            new CountryViewModel{Id= 39,Name= "Finland",NamePersian="فنلاند"},
            new CountryViewModel{Id= 40,Name= "Ukraine",NamePersian="اوکراین"},
            new CountryViewModel{Id= 41,Name= "Russia",NamePersian="روسیه"},
            new CountryViewModel{Id= 42,Name= "Bulgaria",NamePersian="بلغارستان"},
            new CountryViewModel{Id= 43,Name="Turkey",NamePersian="ترکیه"},
            new CountryViewModel{Id= 44,Name= "Greece",NamePersian="یونان"},
            new CountryViewModel{Id= 45,Name= "Japan",NamePersian="ژاپن"},
            new CountryViewModel{Id= 46,Name= "",NamePersian=""},
            new CountryViewModel{Id= 47,Name= "South Korea",NamePersian="کره جنوبی"},
            new CountryViewModel{Id= 48,Name= "India",NamePersian="هند"},
            new CountryViewModel{Id= 49,Name= "Indonesia",NamePersian="اندونزی"},
            new CountryViewModel{Id= 50,Name= "Australia",NamePersian="استرالیا"},
            new CountryViewModel{Id= 51,Name= "South Africa",NamePersian="آفریقا جنوبی"},
            new CountryViewModel{Id= 52,Name= "Republic of Moldova",NamePersian="مولداوی"},
            new CountryViewModel{Id= 53,Name= "Portugal",NamePersian="پرتقال"},
            new CountryViewModel{Id= 54,Name= "Ireland",NamePersian="ایرلند"},
            new CountryViewModel{Id= 55,Name= "Denmark",NamePersian="دانمارک"},
            new CountryViewModel{Id= 56,Name="Iran",NamePersian="ایران"},
            new CountryViewModel{Id= 57,Name= "Pakistan",NamePersian="پاکستان"},
            new CountryViewModel{Id= 58,Name= "Israel",NamePersian="اسرائیل"},
            new CountryViewModel{Id= 59,Name= "Thailand",NamePersian="تایلند"},
            new CountryViewModel{Id= 60,Name= "",NamePersian=""},
            new CountryViewModel{Id= 61,Name= "Slovenia",NamePersian="اسلوانی"},
            new CountryViewModel{Id= 62,Name= "",NamePersian=""},
            new CountryViewModel{Id= 63,Name= "Croatia",NamePersian="کرواسی"},
            new CountryViewModel{Id= 64,Name= "Chile",NamePersian="شیلی"},
            new CountryViewModel{Id= 65,Name= "Serbia",NamePersian="صربستان"},
            new CountryViewModel{Id= 66,Name= "Malaysia",NamePersian="مالزی"},
            new CountryViewModel{Id= 67,Name= "Philippines",NamePersian="فیلیپین"},
            new CountryViewModel{Id= 68,Name= "Singapore",NamePersian="سنگاپور"},
            new CountryViewModel{Id= 69,Name= "Bosnia and Herzegovina",NamePersian="بوسنی و هرزگوین"},
            new CountryViewModel{Id= 70,Name= "Estonia",NamePersian="استونی"},
            new CountryViewModel{Id= 71,Name= "Latvia",NamePersian="لاتویا"},
            new CountryViewModel{Id= 72,Name= "Lithuania",NamePersian="لیتوانی"},
            new CountryViewModel{Id= 73,Name= "North Korea",NamePersian="کره شمالی"},
            new CountryViewModel{Id= 74,Name= "Uruguay",NamePersian="اروگوئه"},
            new CountryViewModel{Id= 75,Name= "Paraguay",NamePersian="پاراگوئه"},
            new CountryViewModel{Id= 76,Name= "Bolivia",NamePersian="بولووی"},
            new CountryViewModel{Id= 77,Name= "Peru",NamePersian="پرو"},
            new CountryViewModel{Id= 78,Name= "Colombia",NamePersian="کلمبیا"},
            new CountryViewModel{Id= 79,Name= "Republic of Macedonia (FYROM)",NamePersian="مقدونیه"},
            new CountryViewModel{Id= 80,Name= "Montenegro",NamePersian="مونتنگرو"},
            new CountryViewModel{Id= 81,Name= "Republic of China (Taiwan)",NamePersian="تایوان"},
            new CountryViewModel{Id= 82,Name= "Cyprus",NamePersian="قبرس"},
            new CountryViewModel{Id= 83,Name= "Belarus",NamePersian="بلاروس"},
            new CountryViewModel{Id= 84,Name= "New Zealand",NamePersian="نیوزلند"},
            new CountryViewModel{Id= 85,Name= "",NamePersian=""},
            new CountryViewModel{Id= 86,Name= "",NamePersian=""},
            new CountryViewModel{Id= 87,Name= "",NamePersian=""},
            new CountryViewModel{Id= 88,Name= "",NamePersian=""},
            new CountryViewModel{Id= 89,Name= "",NamePersian=""},
            new CountryViewModel{Id= 90,Name= "",NamePersian=""},
            new CountryViewModel{Id= 91,Name= "",NamePersian=""},
            new CountryViewModel{Id= 92,Name= "",NamePersian=""},
            new CountryViewModel{Id= 93,Name= "",NamePersian=""},
            new CountryViewModel{Id= 94,Name= "",NamePersian=""},
            new CountryViewModel{Id= 95,Name= "",NamePersian=""},
            new CountryViewModel{Id= 96,Name= "",NamePersian=""},
            new CountryViewModel{Id= 97,Name= "",NamePersian=""},
            new CountryViewModel{Id= 98,Name= "",NamePersian=""},
            new CountryViewModel{Id= 99,Name= "",NamePersian=""},
            new CountryViewModel{Id= 100,Name= "",NamePersian=""},
            new CountryViewModel{Id= 101,Name= "",NamePersian=""},
            new CountryViewModel{Id= 102,Name= "",NamePersian=""},
            new CountryViewModel{Id= 103,Name= "",NamePersian=""},
            new CountryViewModel{Id= 104,Name= "",NamePersian=""},
            new CountryViewModel{Id= 105,Name= "",NamePersian=""},
            new CountryViewModel{Id= 106,Name= "",NamePersian=""},
            new CountryViewModel{Id= 107,Name= "",NamePersian=""},
            new CountryViewModel{Id= 108,Name= "",NamePersian=""},
            new CountryViewModel{Id= 109,Name= "",NamePersian=""},
            new CountryViewModel{Id= 110,Name= "",NamePersian=""},
            new CountryViewModel{Id= 111,Name= "",NamePersian=""},
            new CountryViewModel{Id= 112,Name= "",NamePersian=""},
            new CountryViewModel{Id= 113,Name= "",NamePersian=""},
            new CountryViewModel{Id= 114,Name= "",NamePersian=""},
            new CountryViewModel{Id= 115,Name= "",NamePersian=""},
            new CountryViewModel{Id= 116,Name= "",NamePersian=""},
            new CountryViewModel{Id= 117,Name= "",NamePersian=""},
            new CountryViewModel{Id= 118,Name= "",NamePersian=""},
            new CountryViewModel{Id= 119,Name= "",NamePersian=""},
            new CountryViewModel{Id= 120,Name= "",NamePersian=""},
            new CountryViewModel{Id= 121,Name= "",NamePersian=""},
            new CountryViewModel{Id= 122,Name= "",NamePersian=""},
            new CountryViewModel{Id= 123,Name= "",NamePersian=""},
            new CountryViewModel{Id= 124,Name= "",NamePersian=""},
            new CountryViewModel{Id= 125,Name= "",NamePersian=""},
            new CountryViewModel{Id= 126,Name= "",NamePersian=""},
            new CountryViewModel{Id= 127,Name= "",NamePersian=""},
            new CountryViewModel{Id= 128,Name= "",NamePersian=""},
            new CountryViewModel{Id= 129,Name= "",NamePersian=""},
            new CountryViewModel{Id= 130,Name= "",NamePersian=""},
            new CountryViewModel{Id= 131,Name= "",NamePersian=""},
            new CountryViewModel{Id= 132,Name= "",NamePersian=""},
            new CountryViewModel{Id= 133,Name= "",NamePersian=""},
            new CountryViewModel{Id= 134,Name= "",NamePersian=""},
            new CountryViewModel{Id= 135,Name= "",NamePersian=""},
            new CountryViewModel{Id= 136,Name= "",NamePersian=""},
            new CountryViewModel{Id= 137,Name= "",NamePersian=""},
            new CountryViewModel{Id= 138,Name= "",NamePersian=""},
            new CountryViewModel{Id= 139,Name= "",NamePersian=""},
            new CountryViewModel{Id= 140,Name= "",NamePersian=""},
            new CountryViewModel{Id= 141,Name= "",NamePersian=""},
            new CountryViewModel{Id= 142,Name= "",NamePersian=""},
            new CountryViewModel{Id= 143,Name= "",NamePersian=""},
            new CountryViewModel{Id= 144,Name= "",NamePersian=""},
            new CountryViewModel{Id= 145,Name= "",NamePersian=""},
            new CountryViewModel{Id= 146,Name= "",NamePersian=""},
            new CountryViewModel{Id= 147,Name= "",NamePersian=""},
            new CountryViewModel{Id= 148,Name= "",NamePersian=""},
            new CountryViewModel{Id= 149,Name= "",NamePersian=""},
            new CountryViewModel{Id= 150,Name= "",NamePersian=""},
            new CountryViewModel{Id= 151,Name= "",NamePersian=""},
            new CountryViewModel{Id= 152,Name= "",NamePersian=""},
            new CountryViewModel{Id= 153,Name= "",NamePersian=""},
            new CountryViewModel{Id= 154,Name= "",NamePersian=""},
            new CountryViewModel{Id= 155,Name= "",NamePersian=""},
            new CountryViewModel{Id= 156,Name= "",NamePersian=""},
            new CountryViewModel{Id= 157,Name= "",NamePersian=""},
            new CountryViewModel{Id= 158,Name= "",NamePersian=""},
            new CountryViewModel{Id= 159,Name= "",NamePersian=""},
            new CountryViewModel{Id= 160,Name= "",NamePersian=""},
            new CountryViewModel{Id= 161,Name= "",NamePersian=""},
            new CountryViewModel{Id= 162,Name= "",NamePersian=""},
            new CountryViewModel{Id= 163,Name= "",NamePersian=""},
            new CountryViewModel{Id= 164,Name= "Saudi Arabia",NamePersian="عربستان"},
            new CountryViewModel{Id= 165,Name= "Egypt",NamePersian="مصر"},
            new CountryViewModel{Id= 166,Name= "United Arab Emirates",NamePersian="امارات"},
            new CountryViewModel{Id= 167,Name= "Albania",NamePersian="آلبانی"},
            new CountryViewModel{Id= 168,Name= "Georgia",NamePersian="گرجستان"},
            new CountryViewModel{Id= 169,Name= "Armenia",NamePersian="ارمنستان"},
            new CountryViewModel{Id= 170,Name= "Nigeria",NamePersian="نیجریه"},
            new CountryViewModel{Id= 171,Name= "Cuba",NamePersian="کوبا"},
            new CountryViewModel{Id= 172,Name= "",NamePersian=""},
            new CountryViewModel{Id= 173,Name= "",NamePersian=""},
            new CountryViewModel{Id= 174,Name= "",NamePersian=""},
            new CountryViewModel{Id= 175,Name= "",NamePersian=""},
            new CountryViewModel{Id= 176,Name= "",NamePersian=""},
            new CountryViewModel{Id= 177,Name= "",NamePersian=""},
            new CountryViewModel{Id= 178,Name= "",NamePersian=""},
            new CountryViewModel{Id= 179,Name= "",NamePersian=""},
            new CountryViewModel{Id= 180,Name= "",NamePersian=""},
            new CountryViewModel{Id= 191,Name= "",NamePersian=""},
            new CountryViewModel{Id= 192,Name= "",NamePersian=""},
            new CountryViewModel{Id= 193,Name= "",NamePersian=""},
            new CountryViewModel{Id= 194,Name= "",NamePersian=""},
            new CountryViewModel{Id= 195,Name= "",NamePersian=""},
            new CountryViewModel{Id= 196,Name= "",NamePersian=""},
            new CountryViewModel{Id= 197,Name= "",NamePersian=""},
            new CountryViewModel{Id= 198,Name= "",NamePersian=""},
            new CountryViewModel{Id= 199,Name= "",NamePersian=""},
            new CountryViewModel{Id= 200,Name= "",NamePersian=""}
        };
    }
}
