using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Erep.DomainClasses.Entities
{
    public class Rank
    {
        public List<string> Ranks = new List<string>(){
                "Recruit",
            "Private",
            "Private*",
            "Private**",
            "Private***",
            "Corporal",
            "Corporal*",
            "Corporal**",
            "Corporal***",
            "Sergeant",
            "Sergeant*",
            "Sergeant**",
            "Sergeant***",
            "Lieutenant",
            "Lieutenant*",
            "Lieutenant**",
            "Lieutenant***",
            "Captain",
            "Captain*",
            "Captain**",
            "Captain***",
            "Major",
            "Major*",
            "Major**",
            "Major***",
            "Commander",
            "Commander *",
            "Commander **",
            "Commander ***",
            "Lt Colonel",
            "Lt Colonel*",
            "Lt Colonel**",
            "Lt Colonel***",
            "Colonel",
            "Colonel*",
            "Colonel**",
            "Colonel***",
            "General",
            "General*",
            "General**",
            "General***",
            "Field Marshal",
            "Field Marshal*",
            "Field Marshal**",
            "Field Marshal***",
             "Supreme Marshal*",
            "Supreme Marshal**",
            "Supreme Marshal***",
            "National Force",
            "National Force*",
            "National Force**",
            "National Force***",
            "World Class Force",
            "World Class Force*",
            "World Class Force**",
            "World Class Force***",
            "Legendary Force",
            "Legendary Force*",
            "Legendary Force**",
            "Legendary Force***",
            "God of War",
            "God of War*",
            "God of War**",
            "God of War***",
            "Titan",
            "Titan*",
            "Titan**",
            "Titan***",
            "Battalion I",
            "Battalion II",
            "Battalion III"
            };
    }
}
